### PR TITLE
Add multi DB support

### LINKED ISSUE #22: Is postgres really supported?
> MySQL (default), Postgres, SQLite and Bind backend included

Apart from the README, I don't see any sign that Postgres is implemented.

### PR DESCRIPTION
**Pull request by manuelmazzuola**
fix #22 

To support more databases `MYSQL_AUTOCONF=true` has been renamed to `AUTOCONF=mysql`, backward compatibility is ensured.
`AUTOCONF` can be either mysql (default), postgres or sqlite.
The configuration flow has been changed a little bit. At first the „well-known“ variables are mapped to 12factor-formatted variables.
The DB setup has been extended for postgres and sqlite.
The `pdns.conf` will be updated with all given 12factor-formatted environment variables. This may be redundant, as all configuration variables may be provided via command line but enables compact configuration via `-e` docker cmdline argument.
Switch from `sh` to `bash` to make the script compliant with `POSIX`.

### CODE REVIEW

**Comment by psi-4ward** [comment]
thx looks not so bad but I've very few time atm. Would take some to investigate

**Comment by psi-4ward** [comment]
currently pdns 4.2 is in alpha1 state. I think we should roll out your pull with the 4.2. would you update your PR to this?

in addition, we should not need to stick to alpine:3.7 anymore so we could try 3.9

**Comment by psi-4ward** [comment]
and to be fair we should add steigr to CONTRIBUTORS in the Dockerfile :)

**Comment by gionn** [comment]
> currently pdns 4.2 is in alpha1 state. I think we should roll out your pull with the 4.2. would you update your PR to this?
> 
> in addition, we should not need to stick to alpine:3.7 anymore so we could try 3.9

I would try to avoid recompiling packages at all if there aren't good reasons to do it (e.g. specific features to enable), and just use the binaries from alpine: they currently have 4.1.5-r1 on alpine:3.9 and they are fast to publish stable releases once they are published (if having an up-to-date pdns is the main reason you prefer compiling from sources).

**Comment by seletskiy** [comment]
@manuelmazzuola any update on this PR?

@gionn agree about re-building binary, `docker build` takes time to complete.

**Comment by manuelmazzuola** [comment]
@seletskiy I've added double Dockerfiles to get powerdns from sources or directly from alpine repositories.
image

**Comment by madmath03** [comment]
I feel like there are many changes involved with this PR...

Some of it are really cool (choose between binary or source, possibility to set property through env var, ...), but there are some others that I don't really understand:
* why reset much of the initial properties that were enabled in pdns.conf (`cache-ttl`, `distributor-threads`, ...) ? This might induce a different behavior than the one originally expected.
* why include `random` in the PDNS dynmodules ?
* why use `-Ofast` while it is not recommended (see https://wiki.gentoo.org/wiki/GCC_optimization#-O)
* you added a `TRACE` option in the entrypoint but did not mention it in the README
* really small detail, but for the sake of consistency with the pdns [original source code](https://github.com/PowerDNS/pdns/blob/rel/auth-4.1.x/modules/gpgsqlbackend/schema.pgsql.sql), wouldn't it be better to rename SQL files to `schema.type.sql` (instead of `type.schema.sql`)

Just to make things clear, I might sound unsatisfied but I actually love the work done here.
I had started working at pretty much the same time on the same subject but did not saw a much more advanced PR had been created in the meantime. Now I'm retrieving much of the work done here until this can be merged and sharing my thoughts on a few tweaks.
So in case it was not clear, awesome contrib :+1:

**Comment by psi-4ward** [comment]
So lets go further. For me it's okay to go with the binary releases from alpine if they are fresh enough.
* Does it bring the sql init files so we can avoid to maintain them?
* Does it bring a reasonable pdns.conf?

Open things:
* `TRACE` Readme explanation
* kick `pdns-backend-random` cause I don't believe anyone would use it.

I'm really thankful for this huge contrib!

**Comment by manuelmazzuola** [comment]
> So lets go further. For me it's okay to go with the binary releases from alpine if they are fresh enough.

Ok, I'll remove the source version from this pr.

**Comment by cardil** [comment]
@manuelmazzuola could you resolve conflicts?

**Comment by cardil** [comment]
@manuelmazzuola could you rebase once again? I'd love to see those changes merged.

Regarthing your changes: I'd like to have option to configure pgsql instead of mysql, but I'd like to setup database externally (with Liquibase).

I propose two main env variables: `BACKEND` with default value of `mysql`, and `CREATE_DB_SCHEMA` with default value of `true`.

In that way, I could have configured pdns with pgsql with `BACKEND=pgsql`, but provision database by myself using `CREATE_DB_SCHEMA=false`.

**Comment by CumpsD** [comment]
Hoping this multi db support makes it, I use Postgres as my main db :)

**Comment by NaPs** [comment]
Hi! I'm pretty interested by using this Docker image with Postgres and thus to see this PR merged :-). Can I do anything to help?

Thank you!

**Comment by manuelmazzuola** [comment]
@NaPs could you try to rebase the PR? 
And @psi-4ward, then are you going to merge that PR or?

**Comment by NaPs** [comment]
Hi!

@manuelmazzuola: I put the merge here: https://github.com/NaPs/docker-powerdns/tree/multidb-support. I cannot update this PR by myself.

I took the liberty of cleaning/removing several commits:

- removed source/binary commits
- removed random backend commit (already removed from upstream)
- removed alpine 3.9 (already upgraded in upstream)
- merged Add multi DB support & fix review commits

Made basic tests using the example provided in the README file and it seems to be working fine.

@psi-4ward I hope this will help you!

Thank you guys!

**Comment by NaPs** [comment]
@manuelmazzuola I just figured out that I changed history on upstream commits before to push yesterday. I just fixed that, please re-push the merge! :-)

**Comment by NaPs** [comment]
Hi @psi-4ward, are you going to merge this PR? :-)

**Comment by NaPs** [comment]
Hi there, for those who are still waiting for this feature to be merged: I finally decided to fork (and maintain) this docker image. It is located at [naps/docker-powerdns](https://github.com/naps/docker-powerdns). The image also provides some extra features like an automatic database schema migration.

For Kubernetes users, I'm also working with the people of [k8s-at-home](https://github.com/k8s-at-home) to provide an [Helm Chart for this image](https://github.com/k8s-at-home/charts/tree/master/charts/powerdns).

.+

**Comment by psi-4ward** [comment]
so guys, you're right. I've not enough time for the bunch of oss.
@NaPs: What if I add you as an contributor to this repo that you can take over further improvements?

**Comment by NaPs** [comment]
Hi there, sorry for my silence. @psi-4ward decided to give me write access on this repo so that I can help him to maintain the project and I decided to abandon my fork in order to integrate all my work into this repo. I'll need some time to ensure that my modifications do not break the existing usage for current users (and unfortunately my spare time is limited right now by the end of year celebrations).

For people who are looking for using this image with Posgres right now, I encourage you to use my fork image but be advised that it will maybe need some minor usage change when coming back to this one.

.+

**Comment by hron84** [comment]
@NaPs could you please tell me where is your image is available on Docker Hub? I'm interested in multi-DB support.

**Comment by gionn** [comment]
🌷

**Pull request closed without merging**
