### PR TITLE
update to version 4.2.0

### PR DESCRIPTION
**Pull request by piula**
see issue https://github.com/psi-4ward/docker-powerdns/issues/28

### CODE REVIEW

**Comment by psi-4ward** [comment]
Did you try it?

**Comment by psi-4ward** [comment]
Thank you for this PR but sadly it did not work.
Implemented in #29 

closes #28

**Comment by piula** [comment]
I had some problems (that's why it's multiple commits), but finally it worked for me. Interesting that you can't get it to work -- what error do you observe?

**Comment by psi-4ward** [comment]
Some errors due to missing ` libmariadb.so.3`

**Pull request closed without merging**
